config/routes.rb
MainStreetStation::Application.routes.draw do

  namespace :fhir do

    resources :Condition, controller: 'conditions',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Conformance, controller: 'conformance', as: 'conformance',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Coverage, controller: 'coverages',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Device, controller: 'devices',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :ExplanationOfBenefit, controller: 'explanation_of_benefits',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :FamilyMemberHistory, controller: 'family_member_histories',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Location, controller: 'locations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Observation, controller: :observations,
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Organization, controller: 'organizations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Patient, controller: 'patients',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Questionnaire, controller: 'questionnaires',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Practitioner, controller: 'practitioners',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :operation_outcomes, only: [:show], defaults: {format: :fhirj}

    get 'metadata', to: 'conformance#show', defaults: {format: :fhirj}
  end

  namespace :trust do
    get 'authentication', to: 'authentication#index'
    get 'authentication/:id', to: 'authentication#show'
  end

  namespace :authenticate do
    post 'facebook', to: 'facebook#create', defaults: {format: :json}
  end

  namespace :user do
    resources :registrations
    resources :sessions, only: [:new, :create, :delete]
    get 'sign_up', to: 'registrations#new'
    resources :passwords
    resources :oauth_sessions, only: [:new]
  end

  post 'login', to: 'user/api_sessions#create', defaults: {format: :json}
  delete 'logout', to: 'user/api_sessions#destroy'

  post '/api_session', to: 'user/api_sessions#create', defaults: {format: :json}
  delete '/api_session', to: 'user/api_sessions#destroy'

  root 'welcomes#index'

=begin
  namespace :registration do
    resources :whitelabel_groups
    resources :whitelabels
    resources :contracts
  end

  resources :whitelabel_groups

  match "/yellow_pages" => YellowPages, :anchor => false

  namespace :directory do
    resources :communities do
      resources :community_roles
    end
    resources :parties
    resources :youcentric_objects
    resources :services do
      resources :youcentric_operations
      resources :youcentric_interfaces
    end
    resources :community_role_kinds
    resources :verbs
  end

=end

end

app/models/directory/community.rb
class Directory::Community < ActiveRecord::Base
  has_many :community_roles, dependent: :destroy, autosave: true
  has_many :registration_whitelabels, class_name: 'Registration::Whitelabel', through: :whitelabel_groups

  accepts_nested_attributes_for :community_roles, allow_destroy: true

  def as_json
    super(include: :community_roles)
  end

end

app/models/directory/community_role.rb
class Directory::CommunityRole < ActiveRecord::Base
  belongs_to :community

  has_many :parties, dependent: :destroy, autosave: true
  has_many :services, dependent: :destroy, autosave: true


  accepts_nested_attributes_for :services, allow_destroy: true
  accepts_nested_attributes_for :parties, allow_destroy: true

  def as_json
    super(include: {services: {}})
  end


end

app/models/directory/community_role_kind.rb
class Directory::CommunityRoleKind < ActiveRecord::Base
end

app/models/directory/service.rb
class Directory::Service < ActiveRecord::Base
  belongs_to :community_role

  has_many :youcentric_operations, dependent: :destroy, autosave: true
  has_many :youcentric_objects, dependent: :destroy, autosave: true

  accepts_nested_attributes_for :youcentric_operations, allow_destroy: true
  accepts_nested_attributes_for :youcentric_objects, allow_destroy: true

  def as_json
    super(include: {youcentric_objects: {}, youcentric_operations: {}})
  end

  private

  def get_youcentric_object(id)
    youcentric_objects.find(id)
  end
end

app/models/directory/verb.rb
class Directory::Verb < ActiveRecord::Base
  belongs_to :youcentric_interface
end

app/models/directory/youcentric_object.rb
class Directory::YoucentricObject < ActiveRecord::Base
  # script - identifies ruby script for database creation
  # conformance profile - fhir-based xml
  # youcentric_object_parent_id - id of youCentric_object that 'has' this as a child
  # state_url - for centrally managed resources, identifies the accessing url

  belongs_to :service
end

app/models/directory/youcentric_operation.rb
class Directory::YoucentricOperation < ActiveRecord::Base
  belongs_to :service
end

app/controllers/directory/communities_controller.rb
class Directory::CommunitiesController < ApplicationController

  respond_to :html, :xml, :json, :js

  def index
    @communities = Directory::Community.all

    respond_to do |format|
      format.html
      format.xml {render :xml => @communities}
      format.json {render :json => @communities}
    end
  end

  def show
    @community = Directory::Community.find(params[:id])
    @community_role_kinds = Directory::CommunityRoleKind.all

    respond_to do |format|
      format.html
      format.xml {render :xml => @community}
      format.json {render :json => @community}
    end
  end

  def new
    @community = Directory::Community.new
    @community_role_kinds = Directory::CommunityRoleKind.all
  end

  def create
    @community = Directory::Community.new(params[:directory_community])
    if @community.save
      respond_to do |format|
        format.html {redirect_to @community, :notice => 'Successfully created network.'}
        format.xml {render :xml => @community}
        format.json {render :json => @community}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role_kinds = Directory::CommunityRoleKind.all
    @community = Directory::Community.find(params[:id])
  end

  def update
    @community = Directory::Community.find(params[:id])
    if @community.update_attributes(params[:directory_community])
      redirect_to @community, :notice  => 'Successfully updated community.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community = Directory::Community.find(params[:id])
    @community.destroy
    redirect_to communities_url, :notice => 'Successfully destroyed community.'
  end

end

app/controllers/directory/community_role_kinds_controller.rb
class Directory::CommunityRoleKindsController < ApplicationController
  def index
    @community_role_kinds = CommunityRoleKind.all
  end

  def show
    @community_role_kind = CommunityRoleKind.find(params[:id])
  end

  def new
    @community_role_kind = CommunityRoleKind.new
  end

  def create
    @community_role_kind = CommunityRoleKind.new(params[:community_role_kind])
    if @community_role_kind.save
      redirect_to @community_role_kind, :notice => 'Successfully created community role kind.'
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role_kind = CommunityRoleKind.find(params[:id])
  end

  def update
    @community_role_kind = CommunityRoleKind.find(params[:id])
    if @community_role_kind.update_attributes(params[:community_role_kind])
      redirect_to @community_role_kind, :notice  => 'Successfully updated community role kind.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community_role_kind = CommunityRoleKind.find(params[:id])
    @community_role_kind.destroy
    redirect_to community_role_kinds_url, :notice => 'Successfully destroyed community role kind.'
  end
end

app/controllers/directory/community_roles_controller.rb
class Directory::CommunityRolesController < ApplicationController
  def index
    @community_roles = CommunityRole.all
  end

  def show
    @community_role = CommunityRole.find(params[:id])
  end

  def new
    @community_role = CommunityRole.new
  end

  def create
    @community_role = CommunityRole.new(params[:community_role])
    if @community_role.save
      respond_to do |format|
        format.html {redirect_to @community_role, :notice => 'Successfully created community role.'}
        format.xml {render :xml => @community_role}
        format.json {render :json => @community_role}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role = CommunityRole.find(params[:id])
  end

  def update
    @community_role = CommunityRole.find(params[:id])
    if @community_role.update_attributes(params[:community_role])
      redirect_to @community_role, :notice  => 'Successfully updated community role.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community_role = CommunityRole.find(params[:id])
    @community_role.destroy
    redirect_to community_roles_url, :notice => 'Successfully destroyed community role.'
  end
end

app/controllers/directory/services_controller.rb
class Directory::ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params[:service])
    if @service.save
      respond_to do |format|
        format.html {redirect_to @service, :notice => 'Successfully created service.'}
        format.xml {render :xml => @service}
        format.json {render :json => @service}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update_attributes(params[:service])
      redirect_to @service, :notice  => 'Successfully updated service.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_url, :notice => 'Successfully destroyed service.'
  end
end

app/controllers/directory/verbs_controller.rb
class Directory::VerbsController < ApplicationController
  def index
    @verbs = Verb.all
  end

  def show
    @verb = Verb.find(params[:id])
  end

  def new
    @verb = Verb.new
  end

  def create
    @verb = Verb.new(params[:verb])
    if @verb.save
      redirect_to @verb, :notice => 'Successfully created verb.'
    else
      render :action => 'new'
    end
  end

  def edit
    @verb = Verb.find(params[:id])
  end

  def update
    @verb = Verb.find(params[:id])
    if @verb.update_attributes(params[:verb])
      redirect_to @verb, :notice  => 'Successfully updated verb.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy
    redirect_to verbs_url, :notice => 'Successfully destroyed verb.'
  end
end

app/controllers/directory/youcentric_interfaces_controller.rb
class Directory::YoucentricInterfacesController < ApplicationController
  def index
    @youcentric_interfaces = YoucentricInterface.all
  end

  def show
    @youcentric_interface = YoucentricInterface.find(params[:id])
  end

  def new
    @youcentric_interface = YoucentricInterface.new
  end

  def create
    @youcentric_interface = YoucentricInterface.new(params[:youcentric_interface])
    if @youcentric_interface.save
      redirect_to @youcentric_interface, :notice => 'Successfully created youcentric interface.'
    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_interface = YoucentricInterface.find(params[:id])
  end

  def update
    @youcentric_interface = YoucentricInterface.find(params[:id])
    if @youcentric_interface.update_attributes(params[:youcentric_interface])
      redirect_to @youcentric_interface, :notice  => 'Successfully updated youcentric interface.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_interface = YoucentricInterface.find(params[:id])
    @youcentric_interface.destroy
    redirect_to youcentric_interfaces_url, :notice => 'Successfully destroyed youcentric interface.'
  end
end

app/controllers/directory/youcentric_objects_controller.rb
class Directory::YoucentricObjectsController < ApplicationController
  def index
    @youcentric_objects = YoucentricObject.all
  end

  def show
    @youcentric_object = YoucentricObject.find(params[:id])
  end

  def new
    @youcentric_object = YoucentricObject.new
  end

  def create
    @youcentric_object = YoucentricObject.new(params[:youcentric_object])
    if @youcentric_object.save
      respond_to do |format|
        format.html {redirect_to @youcentric_object, :notice => 'Successfully created youcentric object.'}
        format.xml {render :xml => @youcentric_object}
        format.json {render :json => @youcentric_object}
        end
    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_object = YoucentricObject.find(params[:id])
  end

  def update
    @youcentric_object = YoucentricObject.find(params[:id])
    if @youcentric_object.update_attributes(params[:youcentric_object])
      redirect_to @youcentric_object, :notice  => 'Successfully updated youcentric object.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_object = YoucentricObject.find(params[:id])
    @youcentric_object.destroy
    redirect_to youcentric_objects_url, :notice => 'Successfully destroyed youcentric object.'
  end
end

app/controllers/directory/youcentric_operations_controller.rb
class Directory::YoucentricOperationsController < ApplicationController
  def index
    @youcentric_operations = YoucentricOperation.all
  end

  def show
    @youcentric_operation = YoucentricOperation.find(params[:id])
  end

  def new
    @youcentric_operation = YoucentricOperation.new
  end

  def create
    @youcentric_operation = YoucentricOperation.new(params[:youcentric_operation])
    if @youcentric_operation.save
      respond_to do |format|
        format.html {redirect_to @youcentric_operation, :notice => 'Successfully created youcentric operation.'}
        format.xml {render :xml => @youcentric_operation}
        format.json {render :json => @youcentric_operation}
      end

    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_operation = YoucentricOperation.find(params[:id])
  end

  def update
    @youcentric_operation = YoucentricOperation.find(params[:id])
    if @youcentric_operation.update_attributes(params[:youcentric_operation])
      redirect_to @youcentric_operation, :notice  => 'Successfully updated youcentric operation.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_operation = YoucentricOperation.find(params[:id])
    @youcentric_operation.destroy
    redirect_to youcentric_operations_url, :notice => 'Successfully destroyed youcentric operation.'
  end
end

app/views/directory/communities/_community_role_fields.html.erb
<%= nested_form_for @community_role_kinds do |f| %>
  <p class="fields">
    <strong>Role: </strong><br />
    <ul>
      <%= f.label :name, 'Role Name' %>
      <%= f.text_field :name %>
      <br />
      <%= f.label :description, 'Role Description' %>
      <%= f.text_field :description %>
      <br />
      <%= f.label :role_kind, 'Role Type' %>
      <%= f.select :role_kind, Directory::CommunityRoleKind.all.collect{ |r| [r.name, r.id]} %>

      <br />
      <%= f.link_to_remove 'Remove this Role' %>
    </ul>

    <%= f.fields_for :services %>
    <p>
      <%= f.link_to_add 'See how this Role shares information', :services %>
    </p>
  </p>
<% end %>

app/views/directory/communities/_form.html.erb
<%= nested_form_for @communities do |f| %>
  <%= f.error_messages %>
  Community: <br />
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :objective %><br />
    <%= f.text_field :objective %>
  </p>
  <%= f.fields_for :community_roles %>
  <p>
    <%= f.link_to_add 'Add a Role', :community_roles %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/directory/communities/_service_fields.html.erb
<%= nested_form_for @services do |f| %>
  <p class="fields">
    <strong> YouCentric Service: </strong> <br />
    <br />
  <table>
    <tr>
      <td>
        <%=  f.label :name %>
      </td>
      <td>
        <%=  f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td>
        <%=  f.label :description %>
      </td>
      <td>
        <%=  f.text_field :description %>
      </td>
    </tr>
  </table>

  <%= f.fields_for :youcentric_operations %>
  <p>
    <%= f.link_to_add 'Add an Operation?', :youcentric_operations %>
  </p>

  <%= f.fields_for :youcentric_objects %>
  <p>
    <%= f.link_to_add 'Add an Object?', :youcentric_objects %>
  </p>
  <%= f.link_to_remove 'Remove Service' %>
  </p>
<% end %>

app/views/directory/communities/_youcentric_object_fields.html.erb
<%= nested_form_for @services do |f| %>
  <p class="fields">
    <strong> YouCentric Object: </strong> <br />
    <br />
    <table>
      <tr>
        <td colspan='1'>
          <%=  f.label :name %>
        </td>
        <td colspan='3' style="text-align: left;">
          <%=  f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :description %>
        </td>
        <td>
          <%=  f.text_area :description, :rows => '3' %>
        </td>
        <td>
          <%=  f.label :design_notes %>
        </td>
        <td>
          <%=  f.text_area :design_notes, :rows => '3' %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :script  %>
        </td>
        <td>
          <%=  f.text_area :script, :rows => '5'  %>
        </td>
        <td>
          <%=  f.label :conformance_profile, 'Conformance Profile'  %>
        </td>
        <td>
          <%=  f.text_area :conformance_profile, :rows => '5' %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :youcentric_object_parent_id, 'Parent ID'  %>
        </td>
        <td>
          <%=  f.text_field :youcentric_object_parent_id %>
        </td>
        <td>
          <%=  f.label :state_url, 'URL for Resource' %>
        </td>
        <td>
          <%=  f.text_field :state_url %>
        </td>
      </tr>
    </table>
    <%= f.link_to_remove 'Remove Object' %>
  </p>
<% end %>

app/views/directory/communities/_youcentric_operation_fields.html.erb
<%= nested_form_for @youcentric_operation_fields do |f| %>
  <p class="fields">
    <strong> YouCentric Operation: </strong> <br />
    <br />
    <table>
      <tr>
        <td>
          <%=  f.label :name %>
        </td>
        <td>
          <%=  f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :description %>
        </td>
        <td>
          <%=  f.text_field :description %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :verb_id, 'Verb' %>
        </td>
        <td>
          <%= f.select :verb_id, Directory::Verb.all.collect{ |r| [r.name, r.id]}, :include_blank => true %>
        </td>
      </tr>
    </table>

    <%= f.link_to_remove 'Remove Operation' %>
  </p>
<% end %>

app/views/directory/communities/edit.html.erb
<h2>Edit a Network</h2>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @community %> |
  <%=# link_to 'View All', directory_communities_path %>
</p>

app/views/directory/communities/index.html.erb
<% title 'YouCentric Networks' %>
<table>
  <tr>
    <th>Name</th>
    <th>Objective</th>
  </tr>
  <% @communities.each do |community| %>
    <tr>
      <td><%= community.name %></td>
      <td><%#= community.objective %></td>
      <td><%#= link_to 'Show', directory_communities_path %></td>
      <td><%#= link_to 'Edit', edit_directory_community_path(community) %></td>
    </tr>
  <% end %>
</table>

<p><%#= link_to 'New Community', new_directory_community_path %></p>

app/views/directory/communities/new.html.erb
<% title 'New YouCentric Network' %>

<%= render 'form' %>

<p><%#= link_to 'Back to List', directory_communities_path %></p>

app/views/directory/communities/show.html.erb
<% title 'Network: ' + @community.name %>
<p>
  <strong>Description:</strong>
  <%= @community.description %>
</p>
<p>
  <strong>Objective:</strong>
  <%#= @community.objective %>
</p>

<br />
<table border="3">
  <tr>
    <td style="width: 300px;"><strong>Roles:</strong></td>
    <td style="width: 100px;"><strong>Type:</strong></td>
    <td style="width: 300px;"><strong>Services:</strong></td>
  </tr>
  <tr>
    <% @community.community_roles.each do |community_role| %>
    <td>
      <strong><%=h community_role.name %></strong>
      <ul>
        <%=h community_role.description %>
      </ul>
    </td>
    <td>
      <strong>
        <% @community_role_kinds.select{|v| v['id'] == community_role.role_kind.to_i}.each do |thisHash| %>
          <%= thisHash['name'] %>
        <% end %>
      </strong>
    </td>
    <td>
      <ul>
        <% community_role.services.each do |service| %>

          <li>Name: <%= service.name %></li>
          <li>Description: <%= service.description %></li>

          <% service.youcentric_operations.each do |operation| %>
            <ul>
              <li>Operation: </li>
              <li>
                <ul>
                  <li>Name: <%= operation.name %></li>
                  <li>Description: <%= operation.description %></li>
                  <li>Verb: <%= Directory::Verb.find(operation.verb_id).name unless operation.verb_id.nil? %></li>
                </ul>
              </li>
            </ul>
          <% end %>

          <% service.youcentric_objects.each do |info| %>
            <ul>
              <li>Information: </li>
              <li>
                <ul>
                  <li>Name: <%= info.name %></li>
                  <li>Description: <%= info.description %></li>
                  <li>Parent Object: <%= Directory::YoucentricObject.get_youcentric_object(info.youcentric_object_parent_id).name unless info.youcentric_object_parent_id.nil? %></li>
                  <li>Notes: <%#= info.design_notes %></li>
                  <li>Conformance: <%#= info.conformance_profile %></li>
                </ul>
              </li>
            </ul>
          <% end %>
        <% end %>
      </ul>
    </td>
  <% end %>
  </tr>
</table>


<p>
  <%#= link_to 'Edit', edit_directory_community_path(@community) %> |
  <%= link_to 'Destroy', @community, :confirm => 'Are you sure?', :method => :delete %> |
  <%#= link_to 'View All', directory_communities_path %>
</p>