config/routes.rb
MainStreetStation::Application.routes.draw do

  namespace :fhir do

    resources :Condition, controller: 'conditions',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Conformance, controller: 'conformance', as: 'conformance',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Coverage, controller: 'coverages',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Device, controller: 'devices',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :ExplanationOfBenefit, controller: 'explanation_of_benefits',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :FamilyMemberHistory, controller: 'family_member_histories',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Location, controller: 'locations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Observation, controller: :observations,
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Organization, controller: 'organizations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Patient, controller: 'patients',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Questionnaire, controller: 'questionnaires',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Practitioner, controller: 'practitioners',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :operation_outcomes, only: [:show], defaults: {format: :fhirj}

    get 'metadata', to: 'conformance#show', defaults: {format: :fhirj}
  end

  namespace :trust do
    get 'authentication', to: 'authentication#index'
    get 'authentication/:id', to: 'authentication#show'
  end

  namespace :authenticate do
    post 'facebook', to: 'facebook#create', defaults: {format: :json}
  end

  namespace :user do
    resources :registrations
    resources :sessions, only: [:new, :create, :delete]
    get 'sign_up', to: 'registrations#new'
    resources :passwords
    resources :oauth_sessions, only: [:new]
  end

  post 'login', to: 'user/api_sessions#create', defaults: {format: :json}
  delete 'logout', to: 'user/api_sessions#destroy'

  post '/api_session', to: 'user/api_sessions#create', defaults: {format: :json}
  delete '/api_session', to: 'user/api_sessions#destroy'

  root 'welcomes#index'

=begin
  namespace :registration do
    resources :whitelabel_groups
    resources :whitelabels
    resources :contracts
  end

  resources :whitelabel_groups

  match "/yellow_pages" => YellowPages, :anchor => false

  namespace :directory do
    resources :communities do
      resources :community_roles
    end
    resources :parties
    resources :youcentric_objects
    resources :services do
      resources :youcentric_operations
      resources :youcentric_interfaces
    end
    resources :community_role_kinds
    resources :verbs
  end

=end

end

app/models/directory/community.rb
class Directory::Community < ActiveRecord::Base
  has_many :community_roles, dependent: :destroy, autosave: true
  has_many :registration_whitelabels, class_name: 'Registration::Whitelabel', through: :whitelabel_groups

  accepts_nested_attributes_for :community_roles, allow_destroy: true

  def as_json
    super(include: :community_roles)
  end

end

app/models/directory/community_role.rb
class Directory::CommunityRole < ActiveRecord::Base
  belongs_to :community

  has_many :parties, dependent: :destroy, autosave: true
  has_many :services, dependent: :destroy, autosave: true


  accepts_nested_attributes_for :services, allow_destroy: true
  accepts_nested_attributes_for :parties, allow_destroy: true

  def as_json
    super(include: {services: {}})
  end


end

app/models/directory/community_role_kind.rb
class Directory::CommunityRoleKind < ActiveRecord::Base
end

app/models/directory/service.rb
class Directory::Service < ActiveRecord::Base
  belongs_to :community_role

  has_many :youcentric_operations, dependent: :destroy, autosave: true
  has_many :youcentric_objects, dependent: :destroy, autosave: true

  accepts_nested_attributes_for :youcentric_operations, allow_destroy: true
  accepts_nested_attributes_for :youcentric_objects, allow_destroy: true

  def as_json
    super(include: {youcentric_objects: {}, youcentric_operations: {}})
  end

  private

  def get_youcentric_object(id)
    youcentric_objects.find(id)
  end
end

app/models/directory/verb.rb
class Directory::Verb < ActiveRecord::Base
  belongs_to :youcentric_interface
end

app/models/directory/youcentric_object.rb
class Directory::YoucentricObject < ActiveRecord::Base
  # script - identifies ruby script for database creation
  # conformance profile - fhir-based xml
  # youcentric_object_parent_id - id of youCentric_object that 'has' this as a child
  # state_url - for centrally managed resources, identifies the accessing url

  belongs_to :service
end

app/models/directory/youcentric_operation.rb
class Directory::YoucentricOperation < ActiveRecord::Base
  belongs_to :service
end

app/controllers/directory/communities_controller.rb
class Directory::CommunitiesController < ApplicationController

  respond_to :html, :xml, :json, :js

  def index
    @communities = Directory::Community.all

    respond_to do |format|
      format.html
      format.xml {render :xml => @communities}
      format.json {render :json => @communities}
    end
  end

  def show
    @community = Directory::Community.find(params[:id])
    @community_role_kinds = Directory::CommunityRoleKind.all

    respond_to do |format|
      format.html
      format.xml {render :xml => @community}
      format.json {render :json => @community}
    end
  end

  def new
    @community = Directory::Community.new
    @community_role_kinds = Directory::CommunityRoleKind.all
  end

  def create
    @community = Directory::Community.new(params[:directory_community])
    if @community.save
      respond_to do |format|
        format.html {redirect_to @community, :notice => 'Successfully created network.'}
        format.xml {render :xml => @community}
        format.json {render :json => @community}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role_kinds = Directory::CommunityRoleKind.all
    @community = Directory::Community.find(params[:id])
  end

  def update
    @community = Directory::Community.find(params[:id])
    if @community.update_attributes(params[:directory_community])
      redirect_to @community, :notice  => 'Successfully updated community.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community = Directory::Community.find(params[:id])
    @community.destroy
    redirect_to communities_url, :notice => 'Successfully destroyed community.'
  end

end

app/controllers/directory/community_role_kinds_controller.rb
class Directory::CommunityRoleKindsController < ApplicationController
  def index
    @community_role_kinds = CommunityRoleKind.all
  end

  def show
    @community_role_kind = CommunityRoleKind.find(params[:id])
  end

  def new
    @community_role_kind = CommunityRoleKind.new
  end

  def create
    @community_role_kind = CommunityRoleKind.new(params[:community_role_kind])
    if @community_role_kind.save
      redirect_to @community_role_kind, :notice => 'Successfully created community role kind.'
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role_kind = CommunityRoleKind.find(params[:id])
  end

  def update
    @community_role_kind = CommunityRoleKind.find(params[:id])
    if @community_role_kind.update_attributes(params[:community_role_kind])
      redirect_to @community_role_kind, :notice  => 'Successfully updated community role kind.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community_role_kind = CommunityRoleKind.find(params[:id])
    @community_role_kind.destroy
    redirect_to community_role_kinds_url, :notice => 'Successfully destroyed community role kind.'
  end
end

app/controllers/directory/community_roles_controller.rb
class Directory::CommunityRolesController < ApplicationController
  def index
    @community_roles = CommunityRole.all
  end

  def show
    @community_role = CommunityRole.find(params[:id])
  end

  def new
    @community_role = CommunityRole.new
  end

  def create
    @community_role = CommunityRole.new(params[:community_role])
    if @community_role.save
      respond_to do |format|
        format.html {redirect_to @community_role, :notice => 'Successfully created community role.'}
        format.xml {render :xml => @community_role}
        format.json {render :json => @community_role}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @community_role = CommunityRole.find(params[:id])
  end

  def update
    @community_role = CommunityRole.find(params[:id])
    if @community_role.update_attributes(params[:community_role])
      redirect_to @community_role, :notice  => 'Successfully updated community role.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @community_role = CommunityRole.find(params[:id])
    @community_role.destroy
    redirect_to community_roles_url, :notice => 'Successfully destroyed community role.'
  end
end

app/controllers/directory/services_controller.rb
class Directory::ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params[:service])
    if @service.save
      respond_to do |format|
        format.html {redirect_to @service, :notice => 'Successfully created service.'}
        format.xml {render :xml => @service}
        format.json {render :json => @service}
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update_attributes(params[:service])
      redirect_to @service, :notice  => 'Successfully updated service.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_url, :notice => 'Successfully destroyed service.'
  end
end

app/controllers/directory/verbs_controller.rb
class Directory::VerbsController < ApplicationController
  def index
    @verbs = Verb.all
  end

  def show
    @verb = Verb.find(params[:id])
  end

  def new
    @verb = Verb.new
  end

  def create
    @verb = Verb.new(params[:verb])
    if @verb.save
      redirect_to @verb, :notice => 'Successfully created verb.'
    else
      render :action => 'new'
    end
  end

  def edit
    @verb = Verb.find(params[:id])
  end

  def update
    @verb = Verb.find(params[:id])
    if @verb.update_attributes(params[:verb])
      redirect_to @verb, :notice  => 'Successfully updated verb.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy
    redirect_to verbs_url, :notice => 'Successfully destroyed verb.'
  end
end

app/controllers/directory/youcentric_interfaces_controller.rb
class Directory::YoucentricInterfacesController < ApplicationController
  def index
    @youcentric_interfaces = YoucentricInterface.all
  end

  def show
    @youcentric_interface = YoucentricInterface.find(params[:id])
  end

  def new
    @youcentric_interface = YoucentricInterface.new
  end

  def create
    @youcentric_interface = YoucentricInterface.new(params[:youcentric_interface])
    if @youcentric_interface.save
      redirect_to @youcentric_interface, :notice => 'Successfully created youcentric interface.'
    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_interface = YoucentricInterface.find(params[:id])
  end

  def update
    @youcentric_interface = YoucentricInterface.find(params[:id])
    if @youcentric_interface.update_attributes(params[:youcentric_interface])
      redirect_to @youcentric_interface, :notice  => 'Successfully updated youcentric interface.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_interface = YoucentricInterface.find(params[:id])
    @youcentric_interface.destroy
    redirect_to youcentric_interfaces_url, :notice => 'Successfully destroyed youcentric interface.'
  end
end

app/controllers/directory/youcentric_objects_controller.rb
class Directory::YoucentricObjectsController < ApplicationController
  def index
    @youcentric_objects = YoucentricObject.all
  end

  def show
    @youcentric_object = YoucentricObject.find(params[:id])
  end

  def new
    @youcentric_object = YoucentricObject.new
  end

  def create
    @youcentric_object = YoucentricObject.new(params[:youcentric_object])
    if @youcentric_object.save
      respond_to do |format|
        format.html {redirect_to @youcentric_object, :notice => 'Successfully created youcentric object.'}
        format.xml {render :xml => @youcentric_object}
        format.json {render :json => @youcentric_object}
        end
    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_object = YoucentricObject.find(params[:id])
  end

  def update
    @youcentric_object = YoucentricObject.find(params[:id])
    if @youcentric_object.update_attributes(params[:youcentric_object])
      redirect_to @youcentric_object, :notice  => 'Successfully updated youcentric object.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_object = YoucentricObject.find(params[:id])
    @youcentric_object.destroy
    redirect_to youcentric_objects_url, :notice => 'Successfully destroyed youcentric object.'
  end
end

app/controllers/directory/youcentric_operations_controller.rb
class Directory::YoucentricOperationsController < ApplicationController
  def index
    @youcentric_operations = YoucentricOperation.all
  end

  def show
    @youcentric_operation = YoucentricOperation.find(params[:id])
  end

  def new
    @youcentric_operation = YoucentricOperation.new
  end

  def create
    @youcentric_operation = YoucentricOperation.new(params[:youcentric_operation])
    if @youcentric_operation.save
      respond_to do |format|
        format.html {redirect_to @youcentric_operation, :notice => 'Successfully created youcentric operation.'}
        format.xml {render :xml => @youcentric_operation}
        format.json {render :json => @youcentric_operation}
      end

    else
      render :action => 'new'
    end
  end

  def edit
    @youcentric_operation = YoucentricOperation.find(params[:id])
  end

  def update
    @youcentric_operation = YoucentricOperation.find(params[:id])
    if @youcentric_operation.update_attributes(params[:youcentric_operation])
      redirect_to @youcentric_operation, :notice  => 'Successfully updated youcentric operation.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @youcentric_operation = YoucentricOperation.find(params[:id])
    @youcentric_operation.destroy
    redirect_to youcentric_operations_url, :notice => 'Successfully destroyed youcentric operation.'
  end
end

app/views/directory/community_roles/_form.html.erb
<%= form_for @community_role do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :community_id %><br />
    <%= f.number_field :community_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/directory/community_roles/_invitation_email_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <ul>
      <li><strong>Another YouCentric Account takes on this Role ...</strong></li>
      <li><%= f.label :send_date, 'Date Sent' %>
        <%= f.date_select :send_date %></li>
      <li><%= f.label :content, 'Message' %>
        <%= f.text_area :content, :rows => '3' %></li>
      <li><%= f.label :email_address, 'Email Address' %>
        <%=  f.text_field :email %></li>
      <li><%= f.label :youCentricCenter_id, 'What is their YouCentric ID#?' %>
        <%= f.text_field :youCentricCenter_id %></li>
    </ul>
    <%= f.link_to_remove 'Un-assign' %>
  </p>
<%= end %>

app/views/directory/community_roles/_invitation_id_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <ul>
      <li><strong>Another YouCentric Account takes on this Role ...</strong></li>
      <li>
        <%= f.label :send_date, 'Date Sent' %>
        <%= f.date_select :send_date %>
      </li>
      <li>
        <%= f.label :content, 'Message' %>
        <%= f.text_area :content, :rows => '3' %>
      </li>
      <li>
        <%= f.label :youCentricCenter_id, 'What is their YouCentric ID#?' %>
        <%= f.text_field :youCentricCenter_id %>
      </li>
    </ul>
    <%= f.link_to_remove 'Un-assign' %>
  </p>
<%= end %>

app/views/directory/community_roles/_invitation_you_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <ul>
      <li><strong>You take on this Role ...</strong></li>
      <li><%= f.label :status, 'Do You want to take this Role?' %>
        <%= f.check_box :status %></li>
      <li><%= f.label :send_date, 'Date Accepted' %>
        <%= f.date_select :send_date %></li>
      <li><%= f.text_field :youCentricCenter_id, :hidden => true %></li>
    </ul>

    <%= f.link_to_remove 'Un-assign' %>
  </p>
<%= end %>

app/views/directory/community_roles/_party_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <strong> Assign Roles: </strong> <br />
    <br />
    <ul>
      <%= f.fields_for :invitation_yous %>

      <%= f.link_to_add 'Do You want to take on this Role?', :invitation_yous %>

      <br />

      <%= f.fields_for :invitation_ids %>

      <%= f.link_to_add 'Assign this Role when you know their YouCentric Number?', :invitation_ids %>

      <br />

      <%= f.fields_for :invitation_emails %>

      <%= f.link_to_add 'Assign this Role when you know their YouCentric email?', :invitation_emails %>
    </ul>
  </p>
<% end %>

app/views/directory/community_roles/_service_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <strong> YouCentric Service: </strong> <br />
    <br />
    <table>
      <tr>
        <td>
          <%=  f.label :name %>
        </td>
        <td>
          <%=  f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :description %>
        </td>
        <td>
          <%=  f.text_field :description %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :address %>
        </td>
        <td>
          <%=  f.text_field :address %>
        </td>
      </tr>
    </table>

    <%= f.fields_for :youcentric_operations %>
    <p>
      <%= f.link_to_add 'Add an Operation?', :youcentric_operations %>
    </p>

    <%= f.fields_for :youcentric_objects %>
    <p>
      <%= f.link_to_add 'Add an Object?', :youcentric_objects %>
    </p>
    <%= f.link_to_remove 'Remove Service' %>
  </p>
<% end %>

app/views/directory/community_roles/_youcentric_object_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <strong> YouCentric Object: </strong> <br />
    <br />
    <table>
      <tr>
        <td colspan='1'>
          <%=  f.label :name %>
        </td>
        <td colspan='3' style="text-align: left;">
          <%=  f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :description %>
        </td>
        <td>
          <%=  f.text_area :description, :rows => '3' %>
        </td>
        <td>
          <%=  f.label :design_notes %>
        </td>
        <td>
          <%=  f.text_area :design_notes, :rows => '3' %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :script  %>
        </td>
        <td>
          <%=  f.text_area :script, :rows => '5'  %>
        </td>
        <td>
          <%=  f.label :conformance_profile, 'Conformance Profile'  %>
        </td>
        <td>
          <%=  f.text_area :conformance_profile, :rows => '5' %>
        </td>
      </tr>

      <tr>
        <td>
          <%=  f.label :youcentric_object_parent_id, 'Parent ID'  %>
        </td>
        <td>
          <%=  f.text_field :youcentric_object_parent_id %>
        </td>
        <td>
          <%=  f.label :state_url, 'URL for Resource'  %>
        </td>
        <td>
          <%=  f.text_field :state_url %>
        </td>
      </tr>
    </table>
    <%= f.link_to_remove 'Remove Object' %>
  </p>
<%= end %>

app/views/directory/community_roles/_youcentric_operation_fields.html.erb
<%= nested_form_for @community_roles do |f| %>
  <p class="fields">
    <strong> YouCentric Operation: </strong> <br />
    <br />
    <table>
      <tr>
        <td>
          <%=  f.label :name %>
        </td>
        <td>
          <%=  f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :description %>
        </td>
        <td>
          <%=  f.text_field :description %>
        </td>
      </tr>
      <tr>
        <td>
          <%=  f.label :verb_id, 'Verb' %>
        </td>
        <td>
          <%= f.select :verb_id, Verb.all.collect{ |r| [r.name, r.id]}, :include_blank => true %>
        </td>
      </tr>
    </table>

    <%= f.link_to_remove 'Remove Operation' %>
  </p>
<%= end %>

app/views/directory/community_roles/edit.html.erb
<% title 'Edit Community Role' %>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @community_role %> |
  <%#= link_to 'View All', community_roles_path %>
</p>

app/views/directory/community_roles/index.html.erb
<% title 'Community Roles' %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Community</th>
  </tr>
  <% @community_roles.each do |community_role| %>
    <tr>
      <td><%= community_role.name %></td>
      <td><%= community_role.description %></td>
      <td><%= community_role.community_id %></td>
      <td><%= link_to 'Show', community_role %></td>
      <td><%#= link_to 'Edit', edit_community_role_path(community_role) %></td>
      <td><%= link_to 'Destroy', community_role, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%#= link_to 'New Community Role', new_community_role_path %></p>

app/views/directory/community_roles/new.html.erb
<% title 'New Community Role' %>

<%= render 'form' %>

<p><%#= link_to 'Back to List', community_roles_path %></p>

app/views/directory/community_roles/show.html.erb
<% title 'Role' %>
<%= nested_form_for @community_roles do |f| %>
  <p>
    <%#= link_to 'See the Parent Community', community_path(@community_role.community_id) %>
  </p>
  <p>
    <i>Roles talk about the behaviors of parties within networks, as well as what they should and shouldn't do.</i>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @community_role.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @community_role.description %>
  </p>
  <br />
  <%= f.fields_for :parties %>
  <p>
    <%#= f.link_to_add 'Assign this Role to someone', :parties %>
  </p>
  <%= f.fields_for :services %>
  <p>
    <%= f.link_to_add 'See how YouCentric helps you share this information', :services %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <p>
    <%#= link_to 'See the Parent Community', community_path(@community_role.community_id) %>
  </p>
<% end %>