config/routes.rb
MainStreetStation::Application.routes.draw do

  namespace :fhir do

    resources :Condition, controller: 'conditions',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Conformance, controller: 'conformance', as: 'conformance',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Coverage, controller: 'coverages',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :Device, controller: 'devices',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :ExplanationOfBenefit, controller: 'explanation_of_benefits',
              only: [:index, :show], defaults: {format: :fhirj}
    resources :FamilyMemberHistory, controller: 'family_member_histories',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Location, controller: 'locations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Observation, controller: :observations,
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Organization, controller: 'organizations',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Patient, controller: 'patients',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Questionnaire, controller: 'questionnaires',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :Practitioner, controller: 'practitioners',
              only: [:index, :show, :create, :update], defaults: {format: :fhirj}
    resources :operation_outcomes, only: [:show], defaults: {format: :fhirj}

    get 'metadata', to: 'conformance#show', defaults: {format: :fhirj}
  end

  namespace :trust do
    get 'authentication', to: 'authentication#index'
    get 'authentication/:id', to: 'authentication#show'
  end

  namespace :authenticate do
    post 'facebook', to: 'facebook#create', defaults: {format: :json}
  end

  namespace :user do
    resources :registrations
    resources :sessions, only: [:new, :create, :delete]
    get 'sign_up', to: 'registrations#new'
    resources :passwords
    resources :oauth_sessions, only: [:new]
  end

  post 'login', to: 'user/api_sessions#create', defaults: {format: :json}
  delete 'logout', to: 'user/api_sessions#destroy'

  post '/api_session', to: 'user/api_sessions#create', defaults: {format: :json}
  delete '/api_session', to: 'user/api_sessions#destroy'

  root 'welcomes#index'

=begin
  namespace :registration do
    resources :whitelabel_groups
    resources :whitelabels
    resources :contracts
  end

  resources :whitelabel_groups

  match "/yellow_pages" => YellowPages, :anchor => false

  namespace :directory do
    resources :communities do
      resources :community_roles
    end
    resources :parties
    resources :youcentric_objects
    resources :services do
      resources :youcentric_operations
      resources :youcentric_interfaces
    end
    resources :community_role_kinds
    resources :verbs
  end

=end

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Mainstreet Station powered by Youcentric
  </small>
  <nav>
    <ul>
      <li><%= link_to 'Conformance', fhir_conformance_index_path(format: :html), id: 'footer_conformance'%></li>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "mainstreet", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><label>Welcome <%= current_user.email %></label></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', logout_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Register', new_user_registration_path(:protocol => 'https') %></li>
            <li><%= link_to 'Log In', login_path(:protocol => 'http') %></li>
            <li><%= link_to 'Facebook Log In', new_user_oauth_session_path %></li>
            <li><%= link_to 'Google Log In', new_user_oauth_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--<%= yield(:head) %>-->
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer'%>
</div>
</body>
</html>